"""add_previewImage_for_characters_table

Revision ID: 9098c08cfcf4
Revises: fc904096519e
Create Date: 2024-10-22 15:10:41.439147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9098c08cfcf4'
down_revision = 'fc904096519e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previewImage', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('previewImage')

    # ### end Alembic commands ###
