"""add_hostEditorId_onto_characters_table

Revision ID: 447eee4762b7
Revises: 9098c08cfcf4
Create Date: 2024-10-22 19:42:06.360801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447eee4762b7'
down_revision = '9098c08cfcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostEditorId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_characters_hostEditorId_users", 'users', ['hostEditorId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint("fk_characters_hostEditorId_users", type_='foreignkey')
        batch_op.drop_column('hostEditorId')

    # ### end Alembic commands ###
