"""create_character_table

Revision ID: fc904096519e
Revises: a51042f0239d
Create Date: 2024-10-22 08:56:25.349949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc904096519e'
down_revision = 'a51042f0239d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anime_characters',
    sa.Column('animeId', sa.Integer(), nullable=False),
    sa.Column('characterId', sa.Integer(), nullable=False),
    sa.Column('characterType', sa.Enum('major', 'supporting', 'minor'), nullable=False),
    sa.ForeignKeyConstraint(['animeId'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['characterId'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('animeId', 'characterId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
